services:
  KDC:
    build:
      context: ./kerberos
    image: kerberos
    hostname: KDC
    domainname: KDC.sigusr.net
    networks:
      - sigusr.net

  B:
    build:
      context: ./openssh
    image: openssh
    hostname: B
    domainname: B.sigusr.net
    networks:
      - sigusr.net
    depends_on:
      - KDC

  A:
    build:
      context: ./client
    image: client
    hostname: A
    domainname: A.sigusr.net
    tty: true
    networks:
      - sigusr.net
    depends_on:
      - KDC

networks:
  sigusr.net:
    name: sigusr.net